# Site settings
title: Design Portfolio
email: xmaimo@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Frelance web designer and developer, specialising in Jekyll, HTML, and Javascript
baseurl: "/desginer-portfolio" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

twitter_username: xmaimo
github_username:  xmaimo
google_username: xmaimo

permalink: /:categories/:title

links:
    - title: about
      url: /about
    - title: work
      url: /work
    - title: articles
      url: /articles
    - title: hire me
      url: /hire-me

# Build settings
markdown: kramdown
